# Generated by Django 3.1.10 on 2021-05-11 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('blog', '0003_blogindexpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPage',
        ),
    ]
